# NUMPY GİRİŞ (btk akadami)

In [1]:
import numpy as np

In [2]:
benimlistem = [20,30,40]

In [3]:
np.array(benimlistem)

array([20, 30, 40])

In [4]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.arange(0,10,3)

array([0, 3, 6, 9])

# ZEROS

In [6]:
np.zeros(2 ,dtype= int)

array([0, 0])

In [7]:
np.ones((9,9) ,dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

# LİNSPACE (eşit olarak aralıklı sayılar yap(linearşekilde))

In [8]:
np.linspace(0,20,5 , dtype=int)

array([ 0,  5, 10, 15, 20])

# EYE (birim matris)

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# RANDOM 

In [10]:
np.random.randn(10) #adı ütünde random farklı değerler çevirir 

array([ 1.16689192, -0.98697412,  1.07446748,  0.19135656,  1.0664806 ,
       -1.35781916, -1.19035031, -0.59742102,  1.440564  ,  0.91022923])

In [11]:
np.random.randn(4,4) #bunları matriks olarak da döner ve random olarak döndürür. yani kafasına göre.

array([[ 0.95198842, -0.01472581, -0.33277278,  0.08152109],
       [-0.63138165, -0.83646808,  0.37278734, -0.55266494],
       [ 0.56606137,  0.08582911,  1.0360051 , -1.50691823],
       [-0.03336476, -0.9643573 , -0.26220418, -0.19557782]])

In [12]:
np.random.randint(1,10) #her çalıştığında farklı br değer döndürür.

8

In [13]:
np.random.randint(1,10,7) #burda da bir ile on arsası kaç rakam çevirdik yedi yazarak yani ikisi arasında kç rakam olmasını beliledik

array([7, 2, 3, 9, 5, 6, 9])

# random dizileri bir değere eşitlemek

In [14]:
benimNPdizim = np.arange(30)
benimNPdizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
benimRandomdizim = np.random.randint(1,25,6)
benimRandomdizim


array([ 5, 19,  5, 24, 21,  9])

# NUMPY DİZİ METHODLARI 

In [16]:
benimNPdizim.reshape(6,5) # reshape ile tek boyutlu dizileri 2,3 boyutluya çevirebiliriz


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [17]:
print(benimNPdizim.max())
benimNPdizim.min()

29


0

In [18]:
benimNPdizim.argmax() #argmax() methodu ile en yüksek sayı kaçınci indexte bunu öğreniriz.

29

In [19]:
benimNPdizim.argmin() #argmin() methodu ile n düşük sayı kaçıncı indexte bunu görürüz.

0

In [20]:
benimreshapedizim = benimNPdizim.reshape(10,3) #burda da reshape kullanrak kolonlara böldükten sonra bir değişkene atadık dahakolay görebilmek ve istdiğimizde aynıdeğeri çağırabilmek için
benimreshapedizim

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

# NUMPY DİZİ ÇAĞIRMAK VE DEĞİŞKENE ATAMAK

In [21]:
dizi1 = np.arange(0,6)
dizi1

array([0, 1, 2, 3, 4, 5])

In [22]:
dizi1[2:5] # değişken de atayabilriiz istersek = koyarak o indeksler arasında isteğimiz değeri girebiliriz

array([2, 3, 4])

In [23]:
dizibenzeri = dizi1[2:5]
dizibenzeri

array([2, 3, 4])

In [24]:
dizi1

array([0, 1, 2, 3, 4, 5])

# Matrix Giriş 

In [28]:
liste1 = [[10,20,30], [100,200,300] , ["metehan" , "ali" , "hasan"]]
matrixdizi = np.array(liste1)
matrixdizi

array([['10', '20', '30'],
       ['100', '200', '300'],
       ['metehan', 'ali', 'hasan']], dtype='<U11')

In [34]:
matrixdizi[1,2] 


'300'

In [35]:
matrixdizi[1:,2] # bu şekilde kolonları alıyoruz yani sütünları

array(['300', 'hasan'], dtype='<U11')

In [41]:
yeniliste = [[10,20,30] , [40,50,60] , [101,202,303] , [403,504,606] , [22,33,44]]

In [43]:
yenimatrix = np.array(yeniliste)
yenimatrix

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [101, 202, 303],
       [403, 504, 606],
       [ 22,  33,  44]])

In [47]:
yenimatrix[[0,2,4]] # index yerine liste verilip o şekilde matrix çekiyoruz ve dğişkenler geliyor.

array([[ 10,  20,  30],
       [101, 202, 303],
       [ 22,  33,  44]])

# NumPy Dizilierinde Operasynlar (toplama,çıkarma .v.b)

In [53]:
yenidizi = np.random.randint(1,100,20)
yenidizi

array([49, 57, 75, 64, 68, 42, 85, 72, 94, 21, 11, 66, 81,  3, 38, 72, 95,
       60, 76, 39])

In [56]:
büyükdizi = yenidizi > 24 # sadece çıktı verir değişken alamayız değişkene atamadığımız sürece.

In [58]:
yenidizi[büyükdizi] # sadece burada büyük dizileri verir yani yukarıda true dönenleri gösterir.

array([49, 57, 75, 64, 68, 42, 85, 72, 94, 66, 81, 38, 72, 95, 60, 76, 39])

In [61]:
# daga basit yöndetmi şu şekilde :
basitdizi = yenidizi[yenidizi > 24] 
basitdizi
# bu şekilde yeni bir işlem ya da kod saırı açmadan gerekli işlemi yapıp istediğimiz değerleri çekebiliyoruz.

array([49, 57, 75, 64, 68, 42, 85, 72, 94, 66, 81, 38, 72, 95, 60, 76, 39])

# Toplama


In [63]:
sondizi = np.arange(0,25)
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
toplam_sondizi = sondizi + sondizi
toplam_sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

# Çarpma

In [66]:
tooplam_çarpma = sondizi * sondizi
tooplam_çarpma

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

# Çıkarma

In [67]:
toplam_çıkarma = sondizi - sondizi
toplam_çıkarma

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

# Bölme 

In [69]:
toplam_bölme = sondizi / sondizi
toplam_bölme

C:\Users\kulme\AppData\Local\Temp\ipykernel_13148\3195505086.py:1: RuntimeWarning: invalid value encountered in divide
  toplam_bölme = sondizi / sondizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Kare Kök Alma

In [70]:
np.sqrt(sondizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [74]:
print(np.max(sondizi))
print(np.min(sondizi))

24
0
