In [2]:
# firstly İmport Numpy and Pandas
import numpy as np
import pandas as pd

#1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [43]:
soru1 = np.arange(0,30).reshape(15,2)
print(soru1)
soru1.ndim

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


2

#2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [40]:
soru2 = np.random.randint(0,60,60).reshape(5,-1,6)
print(soru2)
print(soru2.shape)
soru2.ndim

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.

[[[33 16 16 58 54 47]
  [45 35 30 14 14  4]]

 [[26 23 38  5  7 24]
  [55 35 57  9 23  4]]

 [[13 54 48 59 29 58]
  [ 0 15 45 45 25 11]]

 [[47 41  5  6  6 39]
  [14 24 29  8 18 33]]

 [[34 14  0 18 54  7]
  [ 6 36 20  1 11 35]]]
(5, 2, 6)


3

#3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [66]:
soru3 = np.arange(0,20).reshape(4,5)
soru33 = soru3.copy()
soru33 = soru3.reshape(-1)
soru3 # yazdırılırsa 2 boyutlu.
soru33 # yazılırsa ki ben bunu tek boyutlu hale eşitledim şu anda tek boyutlu.
soru33.shape
soru33.ndim



# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.


1

#4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [77]:
soru4 = np.array([[1,2,3,4] ,[10,20,30,40,]])
soru4
for x in np.nditer(soru4): # tek tek döndürme olayı bu şekilde yaptım.
    print(x)

soru4.reshape(-1) # sütun olarak vstack komudunu çalıştıramadım teşekkürler.

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.

1
2
3
4
10
20
30
40


array([ 1,  2,  3,  4, 10, 20, 30, 40])

#5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.


In [86]:
soru5 = np.array([5,10,15,20,25,30])
soru55 = np.array([1,2,3,4,5,6])
print(soru5+soru55)
print(soru5*soru55)
print(soru5/soru55)
print(soru5-soru55)

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.

[ 6 12 18 24 30 36]
[  5  20  45  80 125 180]
[5. 5. 5. 5. 5. 5.]
[ 4  8 12 16 20 24]


#6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [111]:
soru6 = np.random.randint(0,101,10)
print(soru6)
print(soru6.sum())
print(soru6.mean())
print(soru6.max())
print(soru6.var())
print(soru6.std())

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.


[69 60 10 31 33 69  0 82 69 86]
509
50.9
86
824.49
28.713933899763717


#7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.


In [125]:
soru7 = np.arange(0,20)
soru77 = np.arange(500,531)
np.concatenate([soru7,soru77] , axis = 0)

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

#8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.


In [142]:
soru8 = np.arange(15,51)
soru88 = np.arange(10,101)
soru888 = np.concatenate([soru8,soru88], axis = 0)
soru888[25:51] = 888
soru888

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.


array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.


In [150]:
soru9 = np.arange(0,40).reshape(8,5)
soru99 = np.arange(320,360).reshape(8,5)
print(np.concatenate([soru9 , soru99] , axis = 0)) #
np.concatenate([soru9 , soru99] , axis = 1)

# array olduğunu type(oluşturulan değişken) olarak bakabilirsiniz.

[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]
 [ 25  26  27  28  29]
 [ 30  31  32  33  34]
 [ 35  36  37  38  39]
 [320 321 322 323 324]
 [325 326 327 328 329]
 [330 331 332 333 334]
 [335 336 337 338 339]
 [340 341 342 343 344]
 [345 346 347 348 349]
 [350 351 352 353 354]
 [355 356 357 358 359]]


array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

#10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.


In [251]:
np.concatenate([soru9 , soru99] , axis = 2) 

AxisError: axis 2 is out of bounds for array of dimension 2

11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.


In [158]:
soru11 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
np.where(soru11 == 5)

(array([ 5, 13], dtype=int64),)

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.


In [163]:
np.where(soru11 % 2 == 0)

(array([ 1,  3,  4,  6,  7,  9, 11], dtype=int64),)

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.



In [164]:
np.where(soru11 > 4)

(array([ 1,  2,  5,  9, 10, 11, 13], dtype=int64),)

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.


In [165]:
np.where(soru11 % 5 == 0)

(array([ 1,  2,  5, 13], dtype=int64),)

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin


In [181]:
np.random.randint(85,101,1)

array([100])

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.



In [189]:
np.random.randint(10,19,9).reshape(3,3)

array([[12, 15, 12],
       [17, 15, 11],
       [14, 12, 18]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.


In [247]:
np.random.randint(35,62)

61

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.


In [250]:
np.array([[3,8] , [10,53] , [3,8] , [10,53] , [3,8] , [10,53] , [3,8] , [10,53] , [3,8] , [10,53]]) 

array([[ 3,  8],
       [10, 53],
       [ 3,  8],
       [10, 53],
       [ 3,  8],
       [10, 53],
       [ 3,  8],
       [10, 53],
       [ 3,  8],
       [10, 53]])